from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
from datetime import datetime, timedelta
import structlog
from beanie import PydanticObjectId

from src.db.models.udhaar import (
    UdhaarContract,
    ContractStatus,
    BillingFrequency,
    UdhaarInvoice,
    UdhaarCustomer,
    UdhaarTransaction,
    CorporateBillingConfig
)
from src.db.models.compliance import ComplianceDocument, ComplianceDocumentType
from src.services.invoice_service import generate_invoice_for_contract
from src.services.notification_service import send_email_notification, send_whatsapp_notification

log = structlog.get_logger()

scheduler = AsyncIOScheduler()


async def run_invoice_generation():
    """
    Daily job — iterates all active recurring contracts.
    Generates invoices for contracts whose billing period has just ended.
    Skips if invoice already exists (idempotent).
    """
    log.info("Invoice scheduler started", timestamp=datetime.utcnow().isoformat())
    now = datetime.utcnow()

    try:
        active_contracts = await UdhaarContract.find(
            UdhaarContract.status == ContractStatus.active,
            UdhaarContract.billing_frequency == BillingFrequency.recurring,
            UdhaarContract.valid_to >= now,
            UdhaarContract.billing_start_date != None,
        ).to_list()

        total_created = 0
        total_skipped = 0

        for contract in active_contracts:
            try:
                result = await generate_invoice_for_contract(
                    contract=contract,
                    reference_date=now,
                )
                total_created += result.get("created_count", 0)
                total_skipped += result.get("skipped_count", 0)

                if result.get("created_count", 0) > 0:
                    log.info(
                        "Invoice generated by scheduler",
                        contract_id=str(contract.id),
                        customer_id=str(contract.customer_id),
                        invoices=result.get("invoices"),
                    )
            except Exception as e:
                log.error(
                    "Failed to generate invoice for contract",
                    contract_id=str(contract.id),
                    error=str(e),
                )
                continue

        log.info(
            "Invoice scheduler completed",
            total_created=total_created,
            total_skipped=total_skipped,
            timestamp=datetime.utcnow().isoformat(),
        )

    except Exception as e:
        log.error("Invoice scheduler failed", error=str(e))


async def run_compliance_reminders():
    """
    Daily job at 9 AM — checks all documents and sends notifications.
    Updates statuses to expired/expiring_soon if needed.
    """
    log.info("Compliance reminders scheduler started", timestamp=datetime.utcnow().isoformat())
    now = datetime.utcnow()
    try:
        documents = await ComplianceDocument.find().to_list()
        for doc in documents:
            if not doc.is_verified:
                continue
            # 1. Update status dynamically if expired
            expiry_naive = doc.expiry_date.replace(tzinfo=None) if doc.expiry_date.tzinfo else doc.expiry_date
            delta = expiry_naive - now
            days_left = delta.days
            
            # If doc is expired and status hasn't been set, update it
            if days_left < 0 and doc.status not in ["expired", "renewal_pending"]:
                doc.status = "expired"
                doc.updated_at = now
                await doc.save()
                log.info("Document expired", doc_id=str(doc.id), doc_type=doc.doc_type_name)
            elif days_left >= 0 and days_left <= 30 and doc.status not in ["expiring_soon", "renewal_pending"]:
                doc.status = "expiring_soon"
                doc.updated_at = now
                await doc.save()

            # 2. Check if a reminder should be sent
            doc_type = await ComplianceDocumentType.get(doc.doc_type_id)
            reminder_days = doc_type.reminder_days if doc_type else [90, 60, 30, 15, 7, 1]
            
            # If days_left matches a target reminder day, and reminder was not sent yet
            if days_left in reminder_days and days_left not in doc.reminders_sent:
                for contact in doc.notify_contacts:
                    msg = (
                        f"Reminder: Your document '{doc.doc_type_name}' (Cert No: {doc.certificate_number}) "
                        f"is expiring in {days_left} days on {expiry_naive.strftime('%d-%b-%Y')}."
                    )
                    
                    if "whatsapp" in contact.via and contact.phone:
                        send_whatsapp_notification(contact.phone, msg)
                        
                    if "email" in contact.via and contact.email:
                        subject = f"Action Required: Expiration Reminder for {doc.doc_type_name}"
                        body = (
                            f"Dear {contact.name},\n\n"
                            f"This notify you that the certificate '{doc.doc_type_name}' "
                            f"(Number: {doc.certificate_number}) issued by '{doc.issuing_authority or 'Unknown'}' "
                            f"is expiring in {days_left} days on {expiry_naive.strftime('%d-%b-%Y')}.\n\n"
                            f"Please renew it soon to avoid any penalties.\n\n"
                            f"Regards,\nFuelFlux Support"
                        )
                        send_email_notification(contact.email, subject, body)
                
                doc.reminders_sent.append(days_left)
                doc.updated_at = now
                await doc.save()
                log.info("Reminder sent for document", doc_id=str(doc.id), days_left=days_left)
                
        log.info("Compliance reminders scheduler completed", timestamp=datetime.utcnow().isoformat())
    except Exception as e:
        log.error("Compliance reminders scheduler failed", error=str(e))


async def run_corporate_billing_generation():
    """
    Daily job at 6 AM — auto consolidated invoice generation.
    Checks configs matching today's day of month.
    """
    log.info("Corporate Billing Auto-Generation started", timestamp=datetime.utcnow().isoformat())
    now = datetime.utcnow()
    try:
        today_day = now.day
        configs = await CorporateBillingConfig.find(CorporateBillingConfig.billing_day == today_day).to_list()
        
        for config in configs:
            # Find all active corporate customers for this pump
            customers = await UdhaarCustomer.find(
                UdhaarCustomer.pump_id == config.pump_id,
                UdhaarCustomer.is_active == True
            ).to_list()
            
            for customer in customers:
                # Find active contract
                contract = await UdhaarContract.find_one(
                    UdhaarContract.customer_id == customer.id,
                    UdhaarContract.status == ContractStatus.active
                )
                if not contract:
                    continue
                
                # Billing period is past 30 days ending yesterday
                cycle_end = (now - timedelta(days=1)).replace(hour=23, minute=59, second=59, microsecond=0)
                cycle_start = (cycle_end - timedelta(days=30)).replace(hour=0, minute=0, second=0, microsecond=0)
                billing_period_label = f"Cycle ending {cycle_end.strftime('%d-%b-%Y')}"
                
                # Check duplicate
                existing = await UdhaarInvoice.find_one(
                    UdhaarInvoice.customer_id == customer.id,
                    UdhaarInvoice.cycle_start == cycle_start,
                    UdhaarInvoice.cycle_end == cycle_end
                )
                if existing:
                    continue
                
                # Find un-invoiced transactions
                txns = await UdhaarTransaction.find(
                    UdhaarTransaction.customer_id == customer.id,
                    UdhaarTransaction.created_at >= cycle_start,
                    UdhaarTransaction.created_at <= cycle_end,
                    UdhaarTransaction.invoice_id == None
                ).to_list()
                
                if not txns:
                    continue
                
                # Perform calculations
                total_amount = sum(t.amount for t in txns)
                gst_rate = config.default_fuel_gst_rate or 0.0
                taxable_amount = total_amount / (1 + gst_rate)
                total_tax = total_amount - taxable_amount
                
                cgst_rate, sgst_rate, igst_rate = 0.0, 0.0, 0.0
                cgst_amount, sgst_amount, igst_amount = 0.0, 0.0, 0.0
                
                if config.default_supply_type == "intrastate":
                    cgst_rate = gst_rate / 2
                    sgst_rate = gst_rate / 2
                    cgst_amount = total_tax / 2
                    sgst_amount = total_tax / 2
                else:
                    igst_rate = gst_rate
                    igst_amount = total_tax
                
                config.last_invoice_number += 1
                invoice_number = f"{config.invoice_prefix}-{config.last_invoice_number:05d}"
                await config.save()
                
                invoice = UdhaarInvoice(
                    contract_id=contract.id,
                    customer_id=customer.id,
                    pump_id=config.pump_id,
                    cycle_start=cycle_start,
                    cycle_end=cycle_end,
                    total_amount=round(taxable_amount, 2),
                    rounded_amount=round(total_amount, 2),
                    status="unpaid",
                    invoice_number=invoice_number,
                    gstin_supplier=config.gstin,
                    gstin_recipient="27AAAAA1111A1Z1",
                    supply_type=config.default_supply_type,
                    cgst_rate=cgst_rate,
                    sgst_rate=sgst_rate,
                    cgst_amount=round(cgst_amount, 2),
                    sgst_amount=round(sgst_amount, 2),
                    igst_rate=igst_rate,
                    igst_amount=round(igst_amount, 2),
                    taxable_amount=round(taxable_amount, 2),
                    total_tax=round(total_tax, 2),
                    billing_period_label=billing_period_label,
                    invoice_pdf_url=f"/uploads/invoices/{invoice_number}.pdf",
                )
                await invoice.insert()
                
                # Link transactions
                for t in txns:
                    t.invoice_id = invoice.id
                    await t.save()
                    
                log.info("Auto-generated corporate invoice", invoice_number=invoice_number, customer=customer.name)
                
                # Send email
                if customer.contact_email:
                    subject = f"Invoice Generated: {invoice_number}"
                    body = (
                        f"Dear {customer.name},\n\n"
                        f"Your consolidated monthly invoice {invoice_number} has been generated.\n"
                        f"Billing Period: {billing_period_label}\n"
                        f"Total Amount Due: INR {invoice.rounded_amount}\n\n"
                        f"Please find the invoice details in your dashboard.\n\n"
                        f"Regards,\nFuelFlux Billing"
                    )
                    send_email_notification(
                        to_email=customer.contact_email,
                        subject=subject,
                        body=body,
                        cc_email=config.cc_email
                    )
                    
        log.info("Corporate Billing Auto-Generation completed", timestamp=datetime.utcnow().isoformat())
    except Exception as e:
        log.error("Corporate Billing Auto-Generation failed", error=str(e))


async def run_overdue_check():
    """
    Daily job at 7 AM — checks outstanding invoices older than 30 days.
    Marks status as overdue and triggers email reminders.
    """
    log.info("Overdue check started", timestamp=datetime.utcnow().isoformat())
    now = datetime.utcnow()
    try:
        thirty_days_ago = now - timedelta(days=30)
        overdue_invoices = await UdhaarInvoice.find(
            UdhaarInvoice.status == "unpaid",
            UdhaarInvoice.invoice_number != None,
            UdhaarInvoice.generated_at <= thirty_days_ago
        ).to_list()
        
        for invoice in overdue_invoices:
            invoice.status = "overdue"
            await invoice.save()
            
            customer = await UdhaarCustomer.get(invoice.customer_id)
            config = await CorporateBillingConfig.find_one(CorporateBillingConfig.pump_id == invoice.pump_id)
            
            log.info("Invoice marked overdue", invoice_number=invoice.invoice_number)
            
            if customer and customer.contact_email:
                subject = f"URGENT: Overdue Invoice Reminder - Invoice {invoice.invoice_number}"
                body = (
                    f"Dear {customer.name},\n\n"
                    f"This is a reminder that Invoice {invoice.invoice_number} generated on "
                    f"{invoice.generated_at.strftime('%d-%b-%Y')} for the amount of INR {invoice.rounded_amount} "
                    f"is now overdue by 30 days.\n\n"
                    f"Please clear the outstanding balance immediately.\n\n"
                    f"Regards,\nFuelFlux Billing"
                )
                send_email_notification(
                    to_email=customer.contact_email,
                    subject=subject,
                    body=body,
                    cc_email=config.cc_email if config else None
                )
                
        log.info("Overdue check completed", timestamp=datetime.utcnow().isoformat())
    except Exception as e:
        log.error("Overdue check failed", error=str(e))


def start_scheduler():
    """Call this from main.py startup event"""
    # 1. Existing Legacy Invoice generation job at midnight
    scheduler.add_job(
        run_invoice_generation,
        trigger=CronTrigger(hour=0, minute=0),
        id="invoice_generation",
        replace_existing=True,
        misfire_grace_time=3600,
    )

    # 2. Compliance Certificate Expiration check daily at 9 AM
    scheduler.add_job(
        run_compliance_reminders,
        trigger=CronTrigger(hour=9, minute=0),
        id="compliance_reminders",
        replace_existing=True,
        misfire_grace_time=3600,
    )

    # 3. Auto Consolidated Invoice generation daily at 6 AM
    scheduler.add_job(
        run_corporate_billing_generation,
        trigger=CronTrigger(hour=6, minute=0),
        id="corporate_billing_generation",
        replace_existing=True,
        misfire_grace_time=3600,
    )

    # 4. Overdue Invoices check daily at 7 AM
    scheduler.add_job(
        run_overdue_check,
        trigger=CronTrigger(hour=7, minute=0),
        id="overdue_invoices_check",
        replace_existing=True,
        misfire_grace_time=3600,
    )

    scheduler.start()
    log.info("Scheduler started successfully with all background jobs registered")


def stop_scheduler():
    """Call this from main.py shutdown event"""
    if scheduler.running:
        scheduler.shutdown()
        log.info("Scheduler stopped")