"""
Invoice Scheduler
==================
APScheduler-based background job.
Runs daily at midnight — checks all active contracts
and generates invoices for completed billing periods.

Install: pip install apscheduler
"""

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from datetime import datetime
import structlog

from src.core.database import SessionLocal
from src.db.models.udhaar import UdhaarContract, ContractStatus, BillingFrequency
from src.services.invoice_service import generate_invoice_for_contract

log = structlog.get_logger()

scheduler = BackgroundScheduler()


def run_invoice_generation():
    """
    Daily job — iterates all active recurring contracts.
    Generates invoices for contracts whose billing period has just ended.
    Skips if invoice already exists (idempotent).
    """
    log.info("Invoice scheduler started", timestamp=datetime.utcnow().isoformat())
    db = SessionLocal()
    now = datetime.utcnow()

    try:
        active_contracts = db.query(UdhaarContract).filter(
            UdhaarContract.status == ContractStatus.active,
            UdhaarContract.billing_frequency == BillingFrequency.recurring,
            UdhaarContract.valid_to >= now,
            UdhaarContract.billing_start_date != None,
        ).all()

        total_created = 0
        total_skipped = 0

        for contract in active_contracts:
            try:
                result = generate_invoice_for_contract(
                    contract=contract,
                    db=db,
                    reference_date=now,
                )
                total_created += result.get("created_count", 0)
                total_skipped += result.get("skipped_count", 0)

                if result.get("created_count", 0) > 0:
                    log.info(
                        "Invoice generated by scheduler",
                        contract_id=contract.id,
                        customer_id=contract.customer_id,
                        invoices=result.get("invoices"),
                    )
            except Exception as e:
                log.error(
                    "Failed to generate invoice for contract",
                    contract_id=contract.id,
                    error=str(e),
                )
                continue

        log.info(
            "Invoice scheduler completed",
            total_created=total_created,
            total_skipped=total_skipped,
            timestamp=datetime.utcnow().isoformat(),
        )

    except Exception as e:
        log.error("Invoice scheduler failed", error=str(e))
    finally:
        db.close()


def start_scheduler():
    """Call this from main.py startup event"""
    scheduler.add_job(
        run_invoice_generation,
        trigger=CronTrigger(hour=0, minute=0),  # Every midnight
        id="invoice_generation",
        replace_existing=True,
        misfire_grace_time=3600,  # If server was down, run within 1 hour
    )
    scheduler.start()
    log.info("Invoice scheduler started — runs daily at midnight")


def stop_scheduler():
    """Call this from main.py shutdown event"""
    if scheduler.running:
        scheduler.shutdown()
        log.info("Invoice scheduler stopped")